# Generated by Django 4.2.7 on 2023-12-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
    ]
